### ISSUE TITLE
Use of u-boot-common.inc

### ISSUE THREAD

**Issue by ycardaillac** [phytec/meta-fresh#1]
Hi,

I'm wondering if :
`require recipes-bsp/u-boot/u-boot-common.inc`

is well included, are you referring to u-boot-common.inc from meta-phytec or from the one in poky?

Best regards,

**Comment by smk-embedded** [comment]
its not well defined, thanks for the notification, we should rename the inc file from meta-phytec. Our inc only deploys the config, so no big deal

**Comment by smk-embedded** [comment]
fix is public now:
https://github.com/phytec/meta-phytec/commit/1ea0bab3d45779b742ca690cfbdc37c939b3e727
hope that removes the confusion
