### ISSUE TITLE
phycore imx8mm can't use imx-boot with uuu

### ISSUE THREAD

**Issue by ycardaillac** [phytec/meta-fresh#2]
Hi,

I'm having a hard time flashing the SoM with uuu, it seems that I have a problem with the imx-boot generated with meta-fresh.

Do you have any fix for this issue?

u-boot commit id : fd46ea0e701920eb205c2bce9d527bf0dec10b59

I'm using the following command : 
`uuu.exe -b emmc_all .\imx-boot .\image.rootfs.wic`

It's working fine with the imx-boot generated from dunfell.

best regards,

**Comment by smk-embedded** [comment]
We do not flash the full .wic with uuu, so its no common test case for us.

Also, u-boot upstream on the imx8mm is currently not scheduled in the next months, very sorry. Your sales guy can request 8mm upstream support from Phytec, so it will get higher priority.

**Comment by ycardaillac** [comment]
Thanks for the quick reply! We'll get back to you on the commercials channels !

Is there a public roadmap we can see on those topics?

**Comment by smk-embedded** [comment]
There is no public roadmap, the release dates are on the public product page -> downloads -> release. Its a bit tricky to understand and you do not get notifications. We are working on a rss feed. What channel would you prefer?
